---

port: 3000

log: core
logger: console

plugins:
    'RPC::REST':
        '/rest/system':
            'System':
                ping:         rpc_ping
                version:      rpc_version
                list_methods: rpc_list_methods
        '/rest/metacpan':
            'MetaCpan':
                search: mc_search
    'RPC::JSON':
        '/rpc/system':
            'System':
                ping:         rpc_ping
                version:      rpc_version
                list_methods: rpc_list_methods
        '/rpc/metacpan':
            'MetaCpan':
                search: mc_search
    'RPC::XML':
        '/rpc/system':
            'System':
                ping:         rpc_ping
                version:      rpc_version
                list_methods: rpc_list_methods
        '/rpc/metacpan':
            'MetaCpan':
                search: mc_search

metacpan:
    endpoint: https://fastapi.metacpan.org/v1/release/_search
